housing_args = "search/hhh"
city_links = {
    "abilene": "https://abilene.craigslist.org/",
    "austin": "https://austin.craigslist.org/",
    "beaumont": "https://beaumont.craigslist.org/",
    "central la": "https://cenla.craigslist.org/",
    "college station": "https://collegestation.craigslist.org/",
    "deep east tx": "https://nacogdoches.craigslist.org/",
    "east tx": "https://easttexas.craigslist.org/",
    "fayetteville": "https://fayar.craigslist.org/",
    "fort smith": "https://fortsmith.craigslist.org/",
    "galveston": "https://galveston.craigslist.org/",
    "houston": "https://houston.craigslist.org/",
    "killeen-temple": "https://killeen.craigslist.org/",
    "lake charles": "https://lakecharles.craigslist.org/",
    "lawton": "https://lawton.craigslist.org/",
    "little rock": "https://littlerock.craigslist.org/",
    "lubbock": "https://lubbock.craigslist.org/",
    "monroe": "https://monroe.craigslist.org/",
    "northwest ok": "https://enid.craigslist.org/",
    "oklahoma city": "https://oklahomacity.craigslist.org/",
    "san angelo": "https://sanangelo.craigslist.org/",
    "san antonio": "https://sanantonio.craigslist.org/",
    "san marcos": "https://sanmarcos.craigslist.org/",
    "shreveport": "https://shreveport.craigslist.org/",
    "stillwater": "https://stillwater.craigslist.org/",
    "texarkana": "https://texarkana.craigslist.org/",
    "texoma": "https://texoma.craigslist.org/",
    "tulsa": "https://tulsa.craigslist.org/",
    "victoria": "https://victoria.craigslist.org/",
    "waco": "https://waco.craigslist.org/",
    "wichita falls": "https://wichitafalls.craigslist.org/",
    "atlanta": "https://atlanta.craigslist.org/",
    "boston": "https://boston.craigslist.org/",
    "chicago": "https://chicago.craigslist.org/",
    "dallas": "https://dallas.craigslist.org/",
    "denver": "https://denver.craigslist.org/",
    "detroit": "https://detroit.craigslist.org/",
    "las vegas": "https://lasvegas.craigslist.org/",
    "los angeles": "https://losangeles.craigslist.org/",
    "miami": "https://miami.craigslist.org/",
    "minneapolis": "https://minneapolis.craigslist.org/",
    "new york": "https://newyork.craigslist.org/",
    "orange co": "https://orangecounty.craigslist.org/",
    "philadelphia": "https://philadelphia.craigslist.org/",
    "phoenix": "https://phoenix.craigslist.org/",
    "portland": "https://portland.craigslist.org/",
    "raleigh": "https://raleigh.craigslist.org/",
    "sacramento": "https://sacramento.craigslist.org/",
    "san diego": "https://sandiego.craigslist.org/",
    "seattle": "https://seattle.craigslist.org/",
    "sf bayarea": "https://sfbay.craigslist.org/",
    "wash dc": "https://washingtondc.craigslist.org/",
    "alabama": "https://geo.craigslist.org/iso/us/al",
    "alaska": "https://geo.craigslist.org/iso/us/ak",
    "arizona": "https://geo.craigslist.org/iso/us/az",
    "arkansas": "https://geo.craigslist.org/iso/us/ar",
    "california": "https://geo.craigslist.org/iso/us/ca",
    "colorado": "https://geo.craigslist.org/iso/us/co",
    "connecticut": "https://geo.craigslist.org/iso/us/ct",
    "dc": "https://geo.craigslist.org/iso/us/dc",
    "delaware": "https://geo.craigslist.org/iso/us/de",
    "florida": "https://geo.craigslist.org/iso/us/fl",
    "georgia": "https://geo.craigslist.org/iso/us/ga",
    "guam": "https://geo.craigslist.org/iso/gu",
    "hawaii": "https://geo.craigslist.org/iso/us/hi",
    "idaho": "https://geo.craigslist.org/iso/us/id",
    "illinois": "https://geo.craigslist.org/iso/us/il",
    "indiana": "https://geo.craigslist.org/iso/us/in",
    "iowa": "https://geo.craigslist.org/iso/us/ia",
    "kansas": "https://geo.craigslist.org/iso/us/ks",
    "kentucky": "https://geo.craigslist.org/iso/us/ky",
    "louisiana": "https://geo.craigslist.org/iso/us/la",
    "maine": "https://geo.craigslist.org/iso/us/me",
    "maryland": "https://geo.craigslist.org/iso/us/md",
    "mass": "https://geo.craigslist.org/iso/us/ma",
    "michigan": "https://geo.craigslist.org/iso/us/mi",
    "minnesota": "https://geo.craigslist.org/iso/us/mn",
    "mississippi": "https://geo.craigslist.org/iso/us/ms",
    "missouri": "https://geo.craigslist.org/iso/us/mo",
    "montana": "https://geo.craigslist.org/iso/us/mt",
    "n carolina": "https://geo.craigslist.org/iso/us/nc",
    "nebraska": "https://geo.craigslist.org/iso/us/ne",
    "nevada": "https://geo.craigslist.org/iso/us/nv",
    "new jersey": "https://geo.craigslist.org/iso/us/nj",
    "new mexico": "https://geo.craigslist.org/iso/us/nm",
    "n hampshire": "https://geo.craigslist.org/iso/us/nh",
    "north dakota": "https://geo.craigslist.org/iso/us/nd",
    "ohio": "https://geo.craigslist.org/iso/us/oh",
    "oklahoma": "https://geo.craigslist.org/iso/us/ok",
    "oregon": "https://geo.craigslist.org/iso/us/or",
    "pennsylvania": "https://geo.craigslist.org/iso/us/pa",
    "puerto rico": "https://geo.craigslist.org/iso/pr",
    "rhode island": "https://geo.craigslist.org/iso/us/ri",
    "s carolina": "https://geo.craigslist.org/iso/us/sc",
    "south dakota": "https://geo.craigslist.org/iso/us/sd",
    "tennessee": "https://geo.craigslist.org/iso/us/tn",
    "texas": "https://geo.craigslist.org/iso/us/tx",
    "utah": "https://geo.craigslist.org/iso/us/ut",
    "vermont": "https://geo.craigslist.org/iso/us/vt",
    "virginia": "https://geo.craigslist.org/iso/us/va",
    "washington": "https://geo.craigslist.org/iso/us/wa",
    "west virginia": "https://geo.craigslist.org/iso/us/wv",
    "wisconsin": "https://geo.craigslist.org/iso/us/wi",
    "wyoming": "https://geo.craigslist.org/iso/us/wy",
    "calgary": "https://calgary.craigslist.org/",
    "edmonton": "https://edmonton.craigslist.org/",
    "halifax": "https://halifax.craigslist.org/",
    "montreal": "https://montreal.craigslist.org/",
    "ottawa": "https://ottawa.craigslist.org/",
    "saskatoon": "https://saskatoon.craigslist.org/",
    "toronto": "https://toronto.craigslist.org/",
    "vancouver": "https://vancouver.craigslist.org/",
    "winnipeg": "https://winnipeg.craigslist.org/",
    "egypt": "https://geo.craigslist.org/iso/eg",
    "ethiopia": "https://geo.craigslist.org/iso/et",
    "ghana": "https://geo.craigslist.org/iso/gh",
    "kenya": "https://geo.craigslist.org/iso/ke",
    "morocco": "https://geo.craigslist.org/iso/ma",
    "south africa": "https://geo.craigslist.org/iso/za",
    "tunisia": "https://geo.craigslist.org/iso/tn",
    "argentina": "https://geo.craigslist.org/iso/ar",
    "bolivia": "https://geo.craigslist.org/iso/bo",
    "brazil": "https://rio.craigslist.org/",
    "canada": "https://www.craigslist.org/about/sites#CA",
    "chile": "https://geo.craigslist.org/iso/cl",
    "colombia": "https://geo.craigslist.org/iso/co",
    "costa rica": "https://geo.craigslist.org/iso/cr",
    "dom republic": "https://geo.craigslist.org/iso/do",
    "ecuador": "https://geo.craigslist.org/iso/ec",
    "el salvador": "https://geo.craigslist.org/iso/sv",
    "guatemala": "https://geo.craigslist.org/iso/gt",
    "mexico": "https://mexicocity.craigslist.org/",
    "nicaragua": "https://geo.craigslist.org/iso/ni",
    "panama": "https://geo.craigslist.org/iso/pa",
    "peru": "https://geo.craigslist.org/iso/pe",
    "united states": "https://www.craigslist.org/about/sites#US",
    "uruguay": "https://geo.craigslist.org/iso/uy",
    "us virgin islands": "https://geo.craigslist.org/iso/vi",
    "venezuela": "https://geo.craigslist.org/iso/ve",
    "bangladesh": "https://geo.craigslist.org/iso/bd",
    "china": "https://shanghai.craigslist.org/",
    "hong kong": "https://geo.craigslist.org/iso/hk",
    "india": "https://bangalore.craigslist.org/",
    "indonesia": "https://geo.craigslist.org/iso/id",
    "iran": "https://geo.craigslist.org/iso/ir",
    "iraq": "https://geo.craigslist.org/iso/iq",
    "israel": "https://telaviv.craigslist.org/",
    "japan": "https://tokyo.craigslist.org/",
    "kuwait": "https://geo.craigslist.org/iso/kw",
    "lebanon": "https://geo.craigslist.org/iso/lb",
    "malaysia": "https://geo.craigslist.org/iso/my",
    "pakistan": "https://geo.craigslist.org/iso/pk",
    "philippines": "https://manila.craigslist.org/",
    "russia": "https://moscow.craigslist.org/",
    "singapore": "https://singapore.craigslist.org/",
    "south korea": "https://geo.craigslist.org/iso/kr",
    "taiwan": "https://geo.craigslist.org/iso/tw",
    "thailand": "https://geo.craigslist.org/iso/th",
    "turkey": "https://geo.craigslist.org/iso/tr",
    "uae": "https://geo.craigslist.org/iso/ae",
    "vietnam": "https://geo.craigslist.org/iso/vn",
    "west bank": "https://geo.craigslist.org/iso/ps",
    "austria": "https://geo.craigslist.org/iso/at",
    "belgium": "https://geo.craigslist.org/iso/be",
    "bulgaria": "https://geo.craigslist.org/iso/bg",
    "croatia": "https://geo.craigslist.org/iso/hr",
    "czech republic": "https://geo.craigslist.org/iso/cz",
    "denmark": "https://geo.craigslist.org/iso/dk",
    "finland": "https://geo.craigslist.org/iso/fi",
    "france": "https://paris.craigslist.org/",
    "germany": "https://berlin.craigslist.org/",
    "greece": "https://geo.craigslist.org/iso/gr",
    "hungary": "https://geo.craigslist.org/iso/hu",
    "iceland": "https://geo.craigslist.org/iso/is",
    "ireland": "https://geo.craigslist.org/iso/ie",
    "italy": "https://rome.craigslist.org/",
    "luxembourg": "https://geo.craigslist.org/iso/lu",
    "netherlands": "https://geo.craigslist.org/iso/nl",
    "norway": "https://geo.craigslist.org/iso/no",
    "poland": "https://geo.craigslist.org/iso/pl",
    "portugal": "https://geo.craigslist.org/iso/pt",
    "romania": "https://geo.craigslist.org/iso/ro",
    "spain": "https://madrid.craigslist.org/",
    "sweden": "https://geo.craigslist.org/iso/se",
    "switzerland": "https://zurich.craigslist.org/",
    "ukraine": "https://geo.craigslist.org/iso/ua",
    "united kingdom": "https://geo.craigslist.org/iso/gb",
    "australia": "https://sydney.craigslist.org/",
    "new zealand": "https://auckland.craigslist.org/"
}

# Generating the link for the search of page
page_link = lambda base_link, page: base_link + housing_args + "#search=1~gallery~" + str(page)
